### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by katerberg** [rofrischmann/fast-loops#19]
Thanks for making a library that is super useful!

Any chance you'd be able to have a changelog for releases? When upgrading, even though we trust SemVer, it is nice to be able to know what is going in so we can look for any red flags on things we use.

Something lightweight like https://keepachangelog.com/en/1.1.0/ would be really helpful if possible.

**Comment by robinweser** [comment]
Generally open to that, but there hasn't been a new release in over 4 years except for 1 security fix recently.
If we plan to add more in the future, I'll make sure to add a changelog!

Will close this for now, feel free to reopen if you wanna continue to discuss :)
